//Generated by 24HRS
package Servlets;

import Controllers.Item_registrationController;
import Models.Stock;
import Controllers.StockController;
import Models.Item_registration;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet(name = "StockServlet", urlPatterns = {"/StockServlet"})

public class StockServlet extends HttpServlet {

    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try (PrintWriter out = response.getWriter()) {

            String action = request.getParameter("action");
            String pattern = "yyyy/MM/dd - HH:mm:ss";
            SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
            String current_date = simpleDateFormat.format(new Date());

            if (action.equals("insert")) {
                int item_registration_id = Integer.parseInt(request.getParameter("item_registration_id"));
                double qty = Double.parseDouble(request.getParameter("qty"));
                double offer_presentage = Double.parseDouble(request.getParameter("offer_presentage"));
                Stock obj = new Stock();
                obj.setItem_registration_id(item_registration_id);
                obj.setQty(qty);
                obj.setOffer_presentage(offer_presentage);
                obj.setDate_time(current_date);
                try {
                    StockController.getInstance().Save(obj);
                    response.getWriter().println("Saved!");
                } catch (Exception ex) {
                    //error
                }
            } else if (action.equals("update")) {
                int stock_id = Integer.parseInt(request.getParameter("stock_id"));
                int item_registration_id = Integer.parseInt(request.getParameter("item_registration_id"));
                double qty = Double.parseDouble(request.getParameter("qty"));
                double offer_presentage = Double.parseDouble(request.getParameter("offer_presentage"));
                Stock obj = new Stock();
                obj.setStock_id(stock_id);
                obj.setItem_registration_id(item_registration_id);
                obj.setQty(qty);
                obj.setOffer_presentage(offer_presentage);
                obj.setDate_time(current_date);
                try {
                    StockController.getInstance().Update(obj);
                    response.getWriter().println("Updated!");
                } catch (Exception ex) {
                    //error
                }

            } else if (action.equals("delete")) {
                int stock_id = Integer.parseInt(request.getParameter("stock_id"));
                Stock obj = new Stock();
                obj.setStock_id(stock_id);
                try {
                    StockController.getInstance().Delete(obj);
                    response.getWriter().println("Updated!");
                } catch (Exception ex) {
                    //error
                }
            } else if (action.equals("serch")) {
                try {
                    List<Stock> list = new ArrayList<>();
                    List stringList = new ArrayList<>();

                    list = StockController.getInstance().SearchAll();
                    for (int i = 0; i < list.size(); i++) {
                        String s = list.get(i).getStock_id() + "_" + list.get(i).getItem_registration_id() + "_" + list.get(i).getQty() + "_" + list.get(i).getOffer_presentage() + "_" + list.get(i).getDate_time() + "_";
                        stringList.add(s);
                    }
                    String b = String.join("~", stringList);
                    response.getWriter().println(b);
                } catch (Exception ex) {
                    //Error
                }

            } else if (action.equals("report")) {
                try {
                    String file = "C:/xampp/htdocs/Reports/report.pdf";

                    Document doc = new Document();

                    PdfWriter.getInstance(doc, new FileOutputStream(file));
                    doc.open();

                    Paragraph topic = new Paragraph();
                    topic.add("Arunonanda Supermarket");
                    topic.setAlignment(Element.ALIGN_LEFT);

                    Paragraph d = new Paragraph();
                    d.add(current_date);
                    d.setAlignment(Element.ALIGN_LEFT);

                    Paragraph para = new Paragraph();
                    para.add("Stock Report");
                    para.setAlignment(Element.ALIGN_CENTER);

                    doc.add(topic);
                    doc.add(d);
                    doc.add(para);
                    doc.add(Chunk.NEWLINE);
                    doc.add(Chunk.NEWLINE);

                    float x[] = {5, 15, 15, 15, 15};

                    PdfPTable table = new PdfPTable(x);
                    table.getDefaultCell().setHorizontalAlignment(Element.ALIGN_CENTER);

                    table.addCell("ID");
                    table.addCell("Item ID");
                    table.addCell("Quantity");
                    table.addCell("Offer");
                    table.addCell("Date");

                    table.setHeaderRows(1);

                    PdfPCell[] cells = table.getRow(0).getCells();
                    for (int i = 0; i < cells.length; i++) {
                        cells[i].setBackgroundColor(BaseColor.LIGHT_GRAY);
                    }

                    List<Stock> list = new ArrayList<>();
                    list = StockController.getInstance().SearchAll();
                    for (int i = 0; i < list.size(); i++) {
                        table.addCell(list.get(i).getStock_id() + "");
                        table.addCell(list.get(i).getItem_registration_id() + "");
                        table.addCell(list.get(i).getQty() + "");
                        table.addCell(list.get(i).getOffer_presentage() + "");
                        table.addCell(list.get(i).getDate_time() + "");

                    }

                    doc.add(table);

                    doc.close();
                    response.getWriter().println("Report Created!");
                } catch (Exception ex) {
                    response.getWriter().println(ex);
                    //Error
                }

            }
        }
    }

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    @Override
    public String getServletInfo() {
        return "Short description";
    }
}
